DROP TABLE IF EXISTS EXPENDITURE_RECORD;
DROP TABLE IF EXISTS EXPENDITURE_CATEGORY_MATCHER;
DROP TABLE IF EXISTS EXPENDITURE_CATEGORY;
DROP TABLE IF EXISTS BANK_STATEMENT;

DROP SEQUENCE IF EXISTS EXPENDITURE_RECORD_SEQ;
DROP SEQUENCE IF EXISTS EXPENDITURE_CATEGORY_MATCHER_SEQ;
DROP SEQUENCE IF EXISTS EXPENDITURE_CATEGORY_SEQ;
DROP SEQUENCE IF EXISTS BANK_STATEMENT_SEQ;

CREATE SEQUENCE EXPENDITURE_RECORD_SEQ start with 100 increment by 1;
CREATE SEQUENCE EXPENDITURE_CATEGORY_MATCHER_SEQ start with 100 increment by 1;
CREATE SEQUENCE EXPENDITURE_CATEGORY_SEQ start with 100 increment by 1;
CREATE SEQUENCE BANK_STATEMENT_SEQ start with 100 increment by 1;

CREATE TABLE EXPENDITURE_CATEGORY (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL UNIQUE,
    PARENT_CATEGORY_ID INT DEFAULT NULL,
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES EXPENDITURE_CATEGORY(ID),
    CONSTRAINT UC_EXPENDITURE_CATEGORY_NAME UNIQUE (NAME)
);

CREATE TABLE EXPENDITURE_CATEGORY_MATCHER (
    ID INT NOT NULL AUTO_INCREMENT,
    PATTERN VARCHAR(50) NOT NULL,
    MATCHER_TYPE_ID VARCHAR(20) NOT NULL,
    EXPENDITURE_CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EXPENDITURE_CATEGORY_ID) REFERENCES EXPENDITURE_CATEGORY(ID)
);

CREATE TABLE BANK_STATEMENT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE EXPENDITURE_RECORD (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(18, 2) NOT NULL,
    EXPENDITURE_CATEGORY_ID INT NOT NULL,
    BANK_STATEMENT_ID INT NOT NULL,
    FOREIGN KEY (EXPENDITURE_CATEGORY_ID) REFERENCES EXPENDITURE_CATEGORY(ID),
    FOREIGN KEY (BANK_STATEMENT_ID) REFERENCES BANK_STATEMENT(ID),
    CONSTRAINT UC_EXPENDITURE_RECORD_NAME UNIQUE (NAME, BANK_STATEMENT_ID)
);